### PR TITLE
Simprints - enrollment plus

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References
* **Issue:** https://app.clickup.com/t/1e0zrnp
* **Related Pull request:**  

###   :gear: branches 
**app**: 
       Origin:feature/simprints_enrollment_plus Target: develop-simprints
**dhis2-android-SDK**: 
       Origin: develop_eyeseetea
**dhis2-rule-engine**: 
       Origin: ec2b39f051acd5f1a28b2cf940e83176857f4d76
### :tophat: What is the goal?

Add the enrollment + feature

### :memo: How is it being implemented?

- [x] Modify BiometricsClient to return possible duplicates
- [x] Create basic dialog to show possible duplicates
- [x] Use TEI search by GUIDs (search online TEIS also)
- [x] Use the download feature if the TEI is not in the local database
- [x] Implement navigation to TEI dashboard on click in a TEI
- [x] Implement download TEI if it's only in server on click in a TEI
- [x] Implement Enroll new to click in the button

### :boom: How can it be tested?

**use case 1** - Create a new TEI and try to create another TEI with the same image then a possible duplicate dialog should be shown
**use case 2** - Click on a row on the Possible duplicate dialog and the app should navigate to TEI dashboard
**use case 3** - Click on a row on the Possible duplicate dialog and the app should download the TEI if it's only in the server previously to navigate to TEI dashboard
**use case 4** - Click on Enroll New button and the dialog should dismiss and the biometrics button should be green and text biometrics completed. To saved TEI should have value in the biometrics attribute.

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [x] Yeap, here you have some screenshots-
device-2021-10-01-093358

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@xurxodev I think there may an error here. Please follow these steps and let me know if you think there's an error or not:
1. You enroll 5 times the same exact picture, always clicking on enroll new, instead of selecting a possible duplicate
2. After reaching 4 results as possible duplicates, the list never shows more. 

It should keep showing all the possible duplicates and not only 4, right? Is it on our side or the enrollment+ is only listing 4 and there's no way to customize that from the enrollment call?

**Comment by ifoche** [comment]
Actually, paying attention to your screenshot, it looks like it must be on our side, because you're showing 5 results and I can never get more than 5, probably because from 5 on in my screen it would produce scroll... does it make sense?

**Comment by xurxodev** [comment]
@ifoche Simprints ID seems to return only 5 results in enrollment plus and search, but I have more. You can view the returned guids by simprints in the logcat:
For example:
For search
2021-10-11 07:31:35.704 19847-19847/org.simprints.dhis2.debug E/SearchTEPresenter - 1117: Search by biometrics 6aaf6d37-61a2-4c47-bf75-1499b8f9f0ff;4b6de757-570c-4914-82c1-82c161df2f27;b9ee30b8-9518-4cb9-a1e6-9d1597cdb2ee;46184799-4a64-4f2d-b42b-6ecc9aae77c6;695b6fa3-70be-4ae5-b4e0-3ad98d9b3441

For enrollment plus
2021-10-11 07:30:26.165 19847-19847/org.simprints.dhis2.debug E/BiometricsClient$handleRegisterResponse$handlePossibleDuplicates - 115: Possible duplicates [4b6de757-570c-4914-82c1-82c161df2f27, b9ee30b8-9518-4cb9-a1e6-9d1597cdb2ee, 46184799-4a64-4f2d-b42b-6ecc9aae77c6, 695b6fa3-70be-4ae5-b4e0-3ad98d9b3441, c32a993d-bfbb-4095-bd51-4ee34ce45e2d]

If the app for you only returns 4, it's possible that simprints is returned a guid removed for you in the app? This scenario has occurred to me some times

**Review by ifoche — APPROVED** [review]
thanks for the clarifications @xurxodev . All sounds good and looks fine according to what Simprints is returning

**Pull request merged**
