### PR TITLE
Fix for slow counting of org units for search results

### PR DESCRIPTION
**Pull request by BurningAXE**
Please refer to the [PR for the core repo](https://github.com/dhis2/dhis2-android-capture-app/pull/3798) for details on the fix

### CODE REVIEW

**Review by xurxodev — APPROVED** [review]
thanks @BurningAXE 

Great performance improvement.

**Review by ifoche — APPROVED** [review]
thanks @BurningAXE

**Comment by BurningAXE** [comment]
Thanks! All credit goes to [Oleksii](https://github.com/dhis2/dhis2-android-capture-app/commits?author=alex-vt)!
FYI, in the original PR a more idiomatic way has been suggested and accepted: 
https://github.com/dhis2/dhis2-android-capture-app/pull/3798/commits/c4fbb993421526f96bf1e66f38b5d5fac71769fe
It should make no difference in performance but you can adopt that when you get a chance just so there's no divergence from the core repo.

**Comment by alex-vt** [comment]
@BurningAXE https://github.com/dhis2/dhis2-android-capture-app/pull/3798 has been merged. The slight difference of implementation (not in performance) should be seamlessly pulled when the upstream changes are merged next time.

**Pull request merged**
