### PR TITLE
[PSI] Feature psi/bring last changes 2.8.2

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References
* **Issue:** https://app.clickup.com/t/865cxzqy9
* **Related Pull request:** https://github.com/EyeSeeTea/dhis2-android-sdk/pull/441

###   :gear: branches 
**app**: 
       Origin: feature-psi/bring_last_changes_2_8_2 Target: develop-psi
**dhis2-android-SDK**: 
       Origin: feature/bring_last_changes_1_8_2

### :tophat: What is the goal?

Bring the last changes in 2.8.2

### :memo: How is it being implemented?

- [x] Merge conflicts

### :boom: How can it be tested?

The customizations in the app should work

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
Sorry @xurxodev but I cannot login. When you enter server + user + pass, the connect button is disabled. Could you please give it a look? Thank you!

**Review by ifoche — CHANGES_REQUESTED** [review]
We have an issue with the versioning here, @xurxodev . In the login page and the about page of the app, the version is no longer showing what it should now:
2.8.2-psi-fork-1 for the app
1.8.2-eyeseetea-fork-1 for the sdk

The dependencies.gradle file seems to be deleted in this version I don't see how to put the version in its place. Could you please add that to your code?

**Comment by xurxodev** [comment]
@ifoche Restored!. I had many problems to restore using the new libs system lib.versions.toml. 
vname without problem only reading documentation and understand were realized the change was solved but with sdk I have many problems because new system don't read well from lib.versions.toml to create buildConfigField from build.gradle.kts. For the sdk version, show (?provider) in about screen.

I executed the app from official branch and they have the same error.

The unique solution until they solve it that I have found is hard-coded sdk version name in the place where the buildConfigField is created

**Review by ifoche — APPROVED** [review]
thanks @xurxodev

**Pull request merged**
