### PR TITLE
Search outside current program" button disabled

### PR DESCRIPTION
**Pull request by alex-vt**
The "Search outside this program" now needs to be hidden on DHIS2 instances with biometrics - currently the condition for hiding is "always".

A constant was used for the condition (instead of removing the button code) to:
* allow quick change of the condition
* minimize the diff from the upstream

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
Thanks @alex-vt 

This PR has changes in the UI side with potential conflicts when it would be necessary to bring last changes of future versions of the app.

There is a very simple solution to do this with minimal code and easiest to maintain.

The strategy would be to realize the changes in the place where there is a logic to decide to show SearchOutsideProgram.

This place is SearchViewModel in the method handleSearchResult. In this method is where the app takes the decision to show it or not. When the button appear or not, the decision is taken here.

Probably the solution would be to modify the condition where decide to add a new SearchResult of the type SearchResult.SearchResultType.SEARCH_OUTSIDE.

Furthermore, we should take in account that only programs with biometrics mode equal to zero o limited should hide the SearchOutsideProgram button, but not always.

**Comment by alex-vt** [comment]
> This place is SearchViewModel in the method handleSearchResult. In this method is where the app takes the decision to show it or not. When the button appear or not, the decision is taken here.
> 
> Probably the solution would be to modify the condition where decide to add a new SearchResult of the type SearchResult.SearchResultType.SEARCH_OUTSIDE.

Thank you for the suggestion. The UI of the existing `SearchResult.SearchResultType.NO_MORE_RESULTS` indeed is almost identical to `SEARCH_OUTSIDE` with the button removed - I've updated the solution from my previous one to the simpler one in the ViewModel.

> Furthermore, we should take in account that only programs with biometrics mode equal to zero o limited should hide the SearchOutsideProgram button, but not always.

It was specifically updated in the requirements that the "Search outside program" button should be gone in all kinds of programs. Forcing the `SearchResultType` to `NO_MORE_RESULTS` does the job anyway.

**Review by xurxodev — APPROVED** [review]
thanks @alex-vt

**Review by ifoche — APPROVED** [review]
thanks @alex-vt @xurxodev

**Pull request merged**
